steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/darkforest-314814/image
      - --cache=true
      - --cache-ttl=XXh
timeout: 6000s
options:
  pool:
    name: "projects/darkforest-314814/locations/us-central1/workerPools/fast-pool"
